spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    work:
      jdbc-url: jdbc:mysql://10.52.181.241:31003/spring_batch
      username: spring
      password: Batch!!
      driver-class-name: com.mysql.cj.jdbc.Driver
    default:
      jdbc-url: jdbc:h2:mem:springdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  profiles: test
  datasource:
    work:
      jdbc-url: jdbc:mysql://10.52.181.241:31003/spring_batch
      username: spring
      password: Batch!!
      driver-class-name: com.mysql.jdbc.Driver
    default:
      jdbc-url: jdbc:h2:mem:springdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver