spring:
  application:
    name: spring-batch-multi-datasource
  main:
    web-application-type: none
  batch:
    jdbc:
      initialize-schema: always

app:
  data-directory: ./data
  datasource:
    batch:
      url: jdbc:h2:file:./data/batch-meta;AUTO_SERVER=TRUE
      username: sa
      password: ""
      driver-class-name: org.h2.Driver
    business:
      url: jdbc:sqlite:./data/business.db
      driver-class-name: org.sqlite.JDBC

demo:
  failure: false
